#!/bin/bash
root@2a734aa7ec27:/# vi /etc/ssh/sshd_config                                                                                                                               
root@2a734aa7ec27:/# cat /etc/passwd                                                                                                                                       
root:x:0:0:root:/root:/bin/bash                                                                                                                                            
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin                                                                                                                            
bin:x:2:2:bin:/bin:/usr/sbin/nologin                                                                                                                                       
sys:x:3:3:sys:/dev:/usr/sbin/nologin  

